### ISSUE TITLE
Unable to load model.

### ISSUE THREAD

**Issue by K0-RR** [oPikaboo/vanilla-foods-enhanced#2]
[Worker-Main-6/WARN]: Unable to load model: 'vafoen:block/orientable' referenced from: vafoen:egg_block#: java.io.FileNotFoundException: vafoen:models/block/orientable.json

**Comment by bleach9** [comment]
hey, thanks for sharing! Yes, the block had a weird looking model when it would be hold in the hand or show weird in the hotbar that has been fixed. Thank you for letting me know!
