### ISSUE TITLE
Bad icon location and name. Missing issues and icon tags in the fabric.mod.json file. Bad homepage tag location.

### ISSUE THREAD

**Issue by K0-RR** [oPikaboo/vanilla-foods-enhanced#4]
The homepage tag redirects to issues instead. Both should be in use.
Mod icon is in the root directory instead of /assets/vafoen/. It's named vafoen.png instead of icon.png

**Comment by bleach9** [comment]
thanks for pointing that out! will be fixed in the upcoming update! :)
