### ISSUE TITLE
Just a little CF tag issue

### ISSUE THREAD

**Issue by YOYOK9** [oPikaboo/vanilla-foods-enhanced#6]
Not a bug per say just wanted to let you know. your version R1.1.0 [FABRIC 1.16 - 1.16.5] doesn't have a fabric tag, so it appears in the Forge mods search when using the CF app. Not a big issue just thought I would let you know incase forge users come in saying "its crashing" without reading the Fabric part. 

Looks like an awesome mod though, keep up the good work!

**Comment by bleach9** [comment]
sadly, they got rid of the fabric tag feature! it's not possible to tag fabric mods as fabric.
thank you for pointing it out though!

**Comment by YOYOK9** [comment]
> sadly, they got rid of the fabric tag feature! it's not possible to tag fabric mods as fabric. thank you for pointing it out though!

Project tags were removed, but individual file tags are still there. Was a file modloader tag issue, not a project tag issue.
